/*
    Memoria 1.8.0 — dynamic consistency boundary store schema install (PostgreSQL)

    Creates the four tables the Entity Framework Core DCB store needs, with their keys, indexes and
    foreign keys. Run this to stand up a Memoria DCB store without writing a migration yourself.

    This is the DCB store, not the streamed one. The two share nothing: if you use both, run this
    alongside 1.8.0-install-postgresql.sql rather than instead of it.

    If you manage this database with EF Core migrations, do NOT run this. Your DbContext derives from
    DcbDbContext, so `dotnet ef migrations add` generates the same schema from the model and keeps
    __EFMigrationsHistory in step. See docs/guides/install-the-store-schema.md.

    Assumes the default table names and the public schema. Identifiers are quoted because EF creates
    them case-sensitively; adjust them if your DbContext maps them elsewhere.

    Safe to run more than once: every object is created IF NOT EXISTS, so re-running adds only what is
    missing. It does not alter or drop anything that already exists.

    The two Tag columns are created with the "C" collation, which compares byte by byte. Tags compare
    ordinally in .NET, so seat:A1 and seat:a1 are two tags; under a linguistic collation they could
    be one, and every boundary naming them would be quietly wider than the code says. Do not relax
    this.
*/

/* ------------------------------------------------------------------- events */
CREATE TABLE IF NOT EXISTS public."DcbEvents" (
    "Position" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EventType" character varying(255) NOT NULL,
    "Data" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(255),
    CONSTRAINT "PK_DcbEvents" PRIMARY KEY ("Position")
);

CREATE INDEX IF NOT EXISTS "IX_DcbEvents_CreatedDate" ON public."DcbEvents" ("CreatedDate");

CREATE INDEX IF NOT EXISTS "IX_DcbEvents_EventType" ON public."DcbEvents" ("EventType");

/* --------------------------------------------------------------- snapshots */
CREATE TABLE IF NOT EXISTS public."DcbSnapshots" (
    "Id" character varying(400) NOT NULL,
    "SnapshotKind" character varying(20) NOT NULL,
    "StoreId" character varying(255) NOT NULL,
    "TagQuery" text NOT NULL,
    "ModelType" character varying(255) NOT NULL,
    "Version" integer NOT NULL,
    "LatestPosition" bigint NOT NULL,
    "Data" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(255),
    "UpdatedDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    CONSTRAINT "PK_DcbSnapshots" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_DcbSnapshots_Kind_StoreId"
    ON public."DcbSnapshots" ("SnapshotKind", "StoreId");

/* --------------------------------------------------------------- tag heads */
CREATE TABLE IF NOT EXISTS public."DcbTagHeads" (
    "Tag" character varying(255) COLLATE "C" NOT NULL,
    "Token" uuid NOT NULL,
    CONSTRAINT "PK_DcbTagHeads" PRIMARY KEY ("Tag")
);

/* --------------------------------------------------------------- event tags */
CREATE TABLE IF NOT EXISTS public."DcbEventTags" (
    "Position" bigint NOT NULL,
    "Tag" character varying(255) COLLATE "C" NOT NULL,
    CONSTRAINT "PK_DcbEventTags" PRIMARY KEY ("Tag", "Position"),
    CONSTRAINT "FK_DcbEventTags_DcbEvents_Position" FOREIGN KEY ("Position")
        REFERENCES public."DcbEvents" ("Position") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_DcbEventTags_Position" ON public."DcbEventTags" ("Position");
